name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      # chạy hằng ngày 00:00 UTC
  workflow_dispatch:          # cho phép bấm run thủ công

permissions:
  contents: write             # cần để push lên nhánh output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: xuansang2005
          # xuất 2 file: bản sáng (ấm) và bản tối (dark)
          outputs: |
            dist/snake.svg?color_snake=#f97316&color_dots=#fde68a,#fb923c,#f97316,#ef4444,#b91c1c
            dist/snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output   # tạo/cập nhật nhánh "output"
          build_dir: dist         # push toàn bộ thư mục dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
